### ISSUE TITLE
Log on shopping cart page 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/upsoauth#26]
--> PHP Warning: Undefined array key "country" in /home/client/public_html/includes/modules/shipping/upsoauth.php on line 241.

I have the same issue in FedEx.  Maybe `update_status()` should return early if `$order->delivery['country']['id']` is empty?

**Comment by scottcwilson** [comment]
Full log: 

```
[01-Mar-2024 02:12:00 America/Indiana/Indianapolis] Request URI: /index.php?main_page=shopping_cart, IP address: *****, Language id 1
#0 /home/client/public_html/includes/modules/shipping/upsoauth.php(241): zen_debug_error_handler()
#1 /home/client/public_html/includes/modules/shipping/upsoauth.php(214): upsoauth->update_status()
#2 /home/client/public_html/includes/modules/shipping/upsoauth.php(62): upsoauth->storefrontInitialization()
#3 /home/client/public_html/includes/classes/shipping.php(91): upsoauth->__construct()
#4 /home/client/public_html/includes/modules/shipping_estimator.php(148): shipping->__construct()
#5 /home/client/public_html/includes/templates/bootstrap/modalboxes/tpl_shipping_estimator.php(19): require('/home/client/p...')
#6 /home/client/public_html/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php(207): require('/home/client/p...')
#7 /home/client/public_html/includes/templates/bootstrap/common/tpl_main_page.php(216): require('/home/client/p...')
#8 /home/client/public_html/index.php(94): require('/home/client/p...')
--> PHP Warning: Undefined array key "country" in /home/client/public_html/includes/modules/shipping/upsoauth.php on line 241.

```

**Comment by proseLA** [comment]
i am not sure about this one.  in my experience, this `$order->delivery['country']` may be selected, but it may not be an array.   where that problem specifically resides...  well, it would require further digging...

how can an address be selected with no country?  this strikes me as a problem somewhere further up the food chain.  and it is something i have encountered in the past.
