### ISSUE TITLE
order country problem

### ISSUE THREAD

**Issue by proseLA** [lat9/upsoauth#41]
i am sporadically getting the following error:

```
--> PHP Warning: Undefined array key "country" in 
/blahBlahBlah/includes/modules/shipping/upsoauth/UpsOAuthApi.php on line 296.
```
now, i think you will want to know how the country id is not set... but i would think lets just let UPS figure out whether the address is correct.  ZC and its address setup has always been problematic to me; and i agree that tracking down how the country is not set would be ideal...  but how about a solution.  from:

https://github.com/lat9/upsoauth/blob/31cb34c05c7127656fad396c2e94805aab116c48/includes/modules/shipping/upsoauth/UpsOAuthApi.php#L296

to:

```php
'StateProvinceCode' => zen_get_zone_code((int)($order->delivery['country']['id'] ?? STORE_COUNTRY), (int)$order->delivery['zone_id'], ''),
```

**Comment by lat9** [comment]
I realize that this was posted *a while* ago, but if you still have that log it's a big help if you post the _entire_ log (including the backtrace).

I'm guessing that neither the country nor zone_it elements are set, since I think that PHP reports only the first issue found on a given line of source.

**Comment by proseLA** [comment]
i do not have that log.

if your guess is correct, then my fix will only address the country problem and NOT the zone_id.  so one could expect to see a new log when encountered.

as i have already implemented this fix on a production site, i will keep a lookout for any new logs related to this issue.

**Comment by proseLA** [comment]
new log.  i am hesitant to now take up your time as there is a small mod that i did.

this client has 2 UPS accounts, one is for packages under 6 lbs, the other account is for over 6 lbs.

that is what `upsoauth2` does; it changes the account number based on weight.  its quote method is:

```php
class upsoauth2 extends upsoauth
{
...
public function quote($method = '')
        {
            if (!class_exists('UpsOAuthApi2')) {
                require DIR_WS_MODULES . 'shipping/upsoauth/UpsOAuthApi2.php';
            }
            $this->upsApi = new UpsOAuthApi2(MODULE_SHIPPING_UPSOAUTH_MODE, $this->debug, $this->logfile);
            return parent::quote($method);
        }
```

and the module is:

```php
class UpsOAuthApi2 extends UpsOAuthApi
    {
        protected function getShipperNumber(): string
        {
            return MODULE_SHIPPING_UPSOAUTH2_SHIPPER_NUMBER;
        }

        protected function getHandlingFee($service_code)
        {
            return MODULE_SHIPPING_UPSOAUTH2_HANDLING_FEE;
        }

    }
```

now i know all of this works, as i have tested thoroughly.  and i am not able to reproduce the error, even though i am going through the same line items...  but i am open to ideas:

```
[16-Dec-2024 16:32:12 America/Florida/Jupiter] Request URI: /shopping_cart.html, IP address: 104.28.50.131, Language id
 1
#0 /home/mystore/includes/modules/shipping/upsoauth/UpsOAuthApi.php(296): zen_debug_error_han
dler()
#1 /home/mystore/includes/modules/shipping/upsoauth/UpsOAuthApi.php(240): UpsOAuthApi->buildR
ateRequest()
#2 /home/mystore/includes/modules/shipping/upsoauth.php(363): UpsOAuthApi->getAllUpsQuotes()
#3 /home/mystore/includes/modules/shipping/upsoauth2.php(43): upsoauth->quote()
#4 /home/mystore/includes/classes/shipping.php(245): upsoauth2->quote()
#5 /home/mystore/includes/modules/shipping_estimator.php(163): shipping->quote()
#6 /home/mystore/includes/templates/someBootstrap/modalboxes/tpl_shipping_estimator.php(19): requir
e('...')
#7 /home/mystore/includes/templates/someBootstrap/templates/tpl_shopping_cart_default.php(212): req
uire('...')
#8 /home/mystore/includes/templates/someBootstrap/common/tpl_main_page.php(226): require('...')
#9 /home/mystore/index.php(94): require('...')
    --> PHP Warning: Undefined array key "zone_id" in /home/mystore/includes/modules/shipping/ups
oauth/UpsOAuthApi.php on line 296.
```

**Comment by lat9** [comment]
I'll keep this active for a while, to see if anyone else has the issue.
